LCD_DISPLAY_ADDRESS = None

LCD_DISPLAY_SDA_PORT = 0

LCD_DISPLAY_SCL_PORT = 0

LCD_NUMBER_OF_LINES = 2

LCD_NUMBER_OF_COLUMNS = 16

INFRARED_SENSOR_PORT = 0

TEMPERATURE_SENSOR_PORT = 0

WATER_SENSOR_PORT = 0

SOIL_SENSOR_PORT = 0

HUM_AND_TEMP_SENSOR_PORT = 0

WATER_PUMP_PORT = 0

PHOTORESISTOR_SENSOR_PORT = 0

LIGHT_LED_PORT = 0

MAX_VALUE_SOIL_SENSOR = 2000

MAX_VALUE_PHOTO_SENSOR = 4000

DEFAULT_CLIENT_ID = "GARDEN_CLIENT"

MQTT_HOST = ""

MQTT_PORT = 0

TOPIC_SENDING_WATER_SENSOR_DATA = "sending_water_sensor_data"

TOPIC_RECEIVING_WATER_SENSOR_DATA = "receiving_water_sensor_data"

TOPIC_SENDING_INFRARED_SENSOR_DATA = "sending_infrared_sensor_data"

TOPIC_RECEIVING_INFRARED_SENSOR_DATA = "receiving_infrared_sensor_data"

TOPIC_SENDING_SOIL_SENSOR_DATA = "sending_soil_sensor_data"

TOPIC_RECEIVING_SOIL_SENSOR_DATA = "receiving_soil_sensor_data"

TOPIC_SENDING_HUM_AND_TEMP_SENSOR_DATA = "sending_hum_and_temp_sensor_data"

TOPIC_RECEIVING_HUM_AND_TEMP_SENSOR_DATA = "receiving_hum_and_temp_sensor_data"

TOPIC_SENDING_PHOTO_SENSOR_DATA = "sending_photo_sensor_data"

TOPIC_RECEIVING_PHOTO_SENSOR_DATA = "receiving_photo_sensor_data"

TOPIC_SENDING_TEMPERATURE_SENSOR_DATA = "sending_temperature_sensor_data"

TOPIC_RECEIVING_TEMPERATURE_SENSOR_DATA = "receiving_temperature_sensor_data"

WIFI_NAME = ""

WIFI_PASSWORD = ""
