INFRARED_SENSOR_PORT = 0

WATER_SENSOR_PORT = 0

SOIL_SENSOR_PORT = 0

HUM_AND_TEMP_SENSOR_PORT = 0

WATER_PUMP_PORT = 0

PHOTORESISTOR_SENSOR_PORT = 0

MIN_VALUE_SOIL_SENSOR = 500

DEFAULT_CLIENT_ID = "GARDEN_CLIENT"

MQTT_HOST = ""

MQTT_PORT = 3000

TOPIC_SENDING_WATER_SENSOR_DATA = "sending_water_sensor_data"

TOPIC_RECEIVING_WATER_SENSOR_DATA = "receiving_water_sensor_data"

TOPIC_SENDING_INFRARED_SENSOR_DATA = "sending_infrared_sensor_data"

TOPIC_RECEIVING_INFRARED_SENSOR_DATA = "receiving_infrared_sensor_data"

TOPIC_SENDING_SOIL_SENSOR_DATA = "sending_soil_sensor_data"

TOPIC_RECEIVING_SOIL_SENSOR_DATA = "receiving_soil_sensor_data"

TOPIC_SENDING_HUM_AND_TEMP_SENSOR_DATA = "sending_hum_and_temp_sensor_data"

TOPIC_RECEIVING_HUM_AND_TEMP_SENSOR_DATA = "receiving_soil_sensor_data"

WIFI_NAME = ""

WIFI_PASSWORD = ""
